2 html home
ClementFra/FranquartClement_3_140222 pull request #14
Opened 2022-02-21 15:50 UTC by ClementFra

close #2

2022-02-22 06:57 UTC, Tutt-J requested changes

2022-02-22 06:57 UTC, Tutt-J commented on index.html
> +    <meta name="keyword" content="gastronomie, menu , restaurant, gastronomique, execption">
Obsolète

2022-02-22 06:57 UTC, Tutt-J commented on index.html
> +        </section>
please use a first div with only icon and input then a section with id about with h1, p and a (not button)

2022-02-22 06:57 UTC, Tutt-J commented on index.html
> +        <section id="menu">
id name is not represnetative of block, maube better id="steps"

2022-02-22 06:57 UTC, Tutt-J commented on index.html
> +            </article>
No article needed juste an ol with li and not li because here we use numbers. Eache li must only have icon and text, we'll add number later with css

2022-02-22 06:57 UTC, Tutt-J commented on index.html
> +            <h3>Restaurants</h3>
it's an h2

2022-02-22 06:57 UTC, Tutt-J commented on index.html
> +                <h3>Nouveau</h3>
mus be inside figure a and it's just a span

2022-02-22 06:57 UTC, Tutt-J commented on index.html
> +                            <h4>La palette du goût<i class="fill far fa-heart fa-2x"></i></h4>
it's an h3. the heart must not be inside title, must be at the end of figaption

2022-02-22 06:57 UTC, Tutt-J commented on index.html
> +        <section id="restaurants">
this section never close

2022-02-22 06:57 UTC, Tutt-J commented on index.html
> +        </ul>
put inside a div

2022-02-24 08:22 UTC, Tutt-J requested changes

2022-02-24 08:22 UTC, Tutt-J commented on index.html
> +            </section>
please use a first div with only icon and input then a section with id about with h1, p and a (not button)

2022-02-24 08:22 UTC, Tutt-J commented on index.html
> +            </ol>
You have to review how ol and li work

2022-02-24 08:22 UTC, Tutt-J commented on index.html
> +        <h3>ohmyfood</h3>
must be inside div

2022-02-26 09:47 UTC, Tutt-J approved these changes

2022-02-26 09:49 UTC, ClementFra commented
merge

2022-02-26 09:49 UTC, merged